kind: pipeline
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update --recursive

- name: npm-install
  image: benwiley4000/emsdk-puppeteer
  commands:
  - npm install

- name: test
  image: benwiley4000/emsdk-puppeteer
  commands:
  - npm test

- name: build
  image: benwiley4000/emsdk-puppeteer
  commands:
  - ./build-bindings.sh
  - ./build-factory-samples-index
  - npm run build
