kind: pipeline
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule init
  - git submodule update --recursive

- name: test
  image: emscripten/emsdk
  commands:
  - apt update -y
  - apt install -y `cat puppeteer-ubuntu-packages.txt`
  - npm install
  - npm test

- name: build
  image: emscripten/emsdk
  commands:
  - npm install
  - ./build-bindings.sh
  - ./build-factory-samples-index
  - npm run build
