#!/usr/bin/env node

const path = require('path');
const fs = require('fs');
const { v4: uuidv4 } = require('uuid');

const pathPrefix = 'factory-samples';
const factorySamplesDirLocalPath = path.join(__dirname, 'public', pathPrefix);

/** @type {string[]} */
const filenames = fs.readdirSync(factorySamplesDirLocalPath);
const factorySamplesIndex = filenames
  .filter((filename) => filename.endsWith('.wav'))
  .map((filename) => {
    return {
      // chop off track number and .wav
      name: filename.slice(3, -4),
      sourceFileId: `/${pathPrefix}/${filename}`,
      id: uuidv4(),
      // track number should be stored in first two characters
      slotNumber: Number(filename.slice(0, 2)),
      // approximate date Volca Sample was released
      dateSampled: new Date('2014-10-01').getTime(),
    };
  })
  .sort((a, b) => a.slotNumber - b.slotNumber);

const factorySamplesIndexPath = path.join(
  __dirname,
  'src',
  'factory-samples.json'
);
fs.writeFileSync(
  factorySamplesIndexPath,
  JSON.stringify(factorySamplesIndex, null, 2)
);
