version: 2.1

jobs:
  install and test:
    docker:
      - image: benwiley4000/emsdk-puppeteer
    working_directory: ~/volca-sampler
    steps:
      - checkout
      - run: git submodule init && git submodule update --recursive
      - run: npm ci
      - run: npm test
      - store_artifacts:
          path: ~/volca-sampler/test/artifacts
      - persist_to_workspace:
          root: ~/volca-sampler
          paths:
            - .

  build app:
    docker:
      - image: benwiley4000/emsdk-puppeteer
    working_directory: ~/volca-sampler
    steps:
      - attach_workspace:
          at: .
      - run: npm run build:normal

  build static html:
    docker:
      - image: benwiley4000/emsdk-puppeteer
    working_directory: ~/volca-sampler
    steps:
      - attach_workspace:
          at: .
      - run: npm run build:static

  complete build and zip:
    docker:
      - image: benwiley4000/emsdk-puppeteer
    working_directory: ~/volca-sampler
    steps:
      - attach_workspace:
          at: .
      - run: npm run build:finish

  deploy:
    docker:
      - image: benwiley4000/emsdk-puppeteer
    working_directory: ~/volca-sampler
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - 'b2:9e:19:9a:08:bf:99:8f:3e:ba:c3:7f:70:da:b4:d1'
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config user.email "therealbenwiley@gmail.com"
            git config user.name "Ben Wiley"
            npm run deploy

workflows:
  build:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - build-static:
          requires:
            - setup
      - build-finish:
          requires:
            - build
            - build-static
      - deploy:
          requires:
            - build-finish
