version: 2.1

jobs:
  pipeline:
    docker:
      - image: benwiley4000/emsdk-puppeteer
    working_directory: ~/volca-sampler
    steps:
      - checkout
      - run: git submodule init && git submodule update --recursive
      - run: npm install
      - run: npm test
      - store_artifacts:
          path: ~/volca-sampler/test/artifacts
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - 'b2:9e:19:9a:08:bf:99:8f:3e:ba:c3:7f:70:da:b4:d1'
      - run:
          name: Deploy to GitHub Pages
          command: |
            git config user.email "therealbenwiley@gmail.com"
            git config user.name "Ben Wiley"
            npm run deploy

workflows:
  build:
    jobs:
      - pipeline
