version: 2.1

jobs:
  pipeline:
    docker:
      - image: benwiley4000/emsdk-puppeteer
    steps:
      - checkout
      - run: git submodule init && git submodule update --recursive
      - run: npm install
      - run: npm test
      - run: npm run build
      - store_artifacts:
          path: /src/test/02 Kick 3 [native] (compressed).wav
      - store_artifacts:
          path: /src/test/02 Kick 3 [wasm] (compressed).wav
      - store_artifacts:
          path: /src/test/02 Kick 3 [native] (uncompressed).wav
      - store_artifacts:
          path: /src/test/02 Kick 3 [wasm] (uncompressed).wav

workflows:
  build:
    jobs:
      - pipeline
